version: '3.7'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}
  static_volume_habhub: {}
  media_volume_habhub: {}

services:
  react_frontend:
    build:
      context: .
      dockerfile: ./compose/production/react-frontend/Dockerfile
    image: habhub_production_react_frontend
    ports:
      - "3000:80"
    command: nginx -g daemon off

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: habhub_production_django
    #container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume_habhub:/app/staticfiles  # <-- bind the static files
      - media_volume_habhub:/app/media  # <-- bind the media files
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    restart: unless-stopped
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: habhub_production_postgres
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: habhub_production_nginx
    container_name: nginx
    depends_on:
      - django
    volumes:
      - production_nginx:/var/log/nginx
      - ./.ssl/whoi_certs:/etc/ssl/whoi_certs/ # bind a local directory with the WHOI SSL certs
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  redis:
    image: redis:6.0

  celeryworker:
    <<: *django
    image: habhub_production_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: habhub_production_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: habhub_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
